### ISSUE TITLE
How should I handle an inverted servo?

### ISSUE THREAD

**Issue by daniellmb** [hybridgroup/cylon-firmata#39]
I realize I can just minus the value from 180 but I'm curious if there is an equivalent to `isInverted` in johnny-five.

https://github.com/rwaldron/johnny-five/wiki/Servo

**Comment by deadprogram** [comment]
Hi, @daniellmb there is not currently, but seems pretty easy to add such a feature. This should be added to https://github.com/hybridgroup/cylon-gpio/issues and we'd love to see a PR, of course!

**Comment by deadprogram** [comment]
Hi, @daniellmb did you see my comment that this is more properly a feature request on cylon-gpio? That is where the servo code is https://github.com/hybridgroup/cylon-gpio/blob/master/lib/servo.js

I'm going to close this issue, if you like please open a new issue on this topic under cylon-gpio.

Thanks!

**Comment by daniellmb** [comment]
yep I did, thanks
